### ISSUE TITLE
OpeningHourTest fails and throws exception

### ISSUE THREAD

**Issue by aoles** [opening-hours/opening_hours.java#1]
Hi,

when trying to run the provided example I got the following error - any hints how to fix this?

Cheers,
Andrzej

```
> java -version
java version "1.8.0_172-ea"
Java(TM) SE Runtime Environment (build 1.8.0_172-ea-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b03, mixed mode)
> java OpeningHourTest "SH off"
Exception in thread "main" javax.script.ScriptException: ReferenceError: "console" is not defined in <eval> at line number 4415
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:199)
	at OpeningHourTest.main(OpeningHourTest.java:32)
Caused by: <eval>:4415 ReferenceError: "console" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1441)
	at jdk.nashorn.internal.scripts.Script$Recompilation$25$246770AA$\^eval\_.L:3957#L:3959#formatLibraryBugMessage(<eval>:4415)
	at jdk.nashorn.internal.scripts.Script$Recompilation$23$349305AAA$\^eval\_.L:3957#L:3959#getSHForYear(<eval>:6310)
	at jdk.nashorn.internal.scripts.Script$Recompilation$21$342203A$\^eval\_.L:3957#L:3959#parseHoliday#selector-1#L:6191(<eval>:6197)
	at jdk.nashorn.internal.scripts.Script$Recompilation$20$392952A$\^eval\_.L:3957#L:3959#getStatePair(<eval>:7178)
	at jdk.nashorn.internal.scripts.Script$Recompilation$19$417292A$\^eval\_.L:3957#L:3959#getIterator#L:7665(<eval>:7670)
	at jdk.nashorn.internal.scripts.Script$Recompilation$18$417254A$\^eval\_.L:3957#L:3959#getIterator(<eval>:7665)
	at jdk.nashorn.internal.scripts.Script$Recompilation$17$410293$\^eval\_.L:3957#L:3959#getWarnings-1(<eval>:7483)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	... 2 more
make: *** [run] Error 1```

**Comment by ypid** [comment]
Should be fixed, thanks for reporting. Refs:

* https://stackoverflow.com/questions/20793089/secure-nashorn-js-execution/48751893#48751893

**Comment by aoles** [comment]
Awesome, thanks a lot for the prompt fix!

**Comment by don-vip** [comment]
Do we need this fix in JOSM too?

**Comment by ypid** [comment]
@don-vip Not sure. I was also wondering but have not checked. I guess it cannot hurt.

@aoles You are welcome.

**Comment by SlowMo24** [comment]
> Do we need this fix in JOSM too?

Hi, 

I don't quite understand how this repo and the main JOSM-repository interact but I ran into this error using JOSM-15155 as a dependency in my Project. So it could be great if you could update `OpeningHourTest.java` in JOSM also. Cheers.

EDIT: just confirmed: this error prevents proper logging of errors to the console in josm-test.jar v15155
EDIT2: https://josm.openstreetmap.de/ticket/17932

**Comment by don-vip** [comment]
@ypid I have reported the fix to JOSM but it breaks localization: https://josm.openstreetmap.de/ticket/17932#comment:7

**Comment by ypid** [comment]
@don-vip Thanks for that! I don’t have more details about this unfortunately so I cannot really help you here. I hope you can figure it out.
